<%@ Page Title="Pedido" Language="C#"  MasterPageFile="~/Site.Master"  AutoEventWireup="true" CodeBehind="Pedido.aspx.cs" Inherits="Trabalho1POO2.WebForm.Paginas.Pedido" %>
<%@ Register Src="~/Componentes/ResumoPedido.ascx" TagPrefix="ex" TagName="ResumoPedido" %>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    <hr/>
    <div runat="server" id="divBtns" visible="false" style="margin-top:10px; margin-bottom:19px;">
        <asp:Button  CssClass="btn btn-success" runat="server" ID="btnComprar" OnClick="btnComprar_Click" Text="Comprar" />
    </div>
    <fieldset>
        <legend>Seleção cliente</legend>
        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="ddlCliente">Cliente:</label>
                    <asp:DropDownList AutoPostBack="true" CssClass="form-control" ID="ddlCliente" runat="server" OnSelectedIndexChanged="ddlCliente_SelectedIndexChanged" />
                </div>
            </div>
        </div>
    </fieldset>
    <div runat="server" id="divItensProdutos" visible="false"> 
        <fieldset>
            <legend>Itens produtos</legend>
            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="txtNome">Produto:</label>
                        <asp:DropDownList CssClass="form-control" AutoPostBack="true" ID="ddlProduto" runat="server" />
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="txtNome">Quantidade:</label>
                        <asp:TextBox CssClass="form-control" runat="server" ID="txtQuantidadeitens" TextMode="Number" />
                    </div>
                </div>
                <div class="col-lg-4" style="display:flex; justify-items:center">
                    <div class="form-group">
                        <label for="btnAdicionarProduto">Adiconar:</label><br />
                        <asp:Button  CssClass="btn btn-default" runat="server" ID="btnAdicionarProduto" OnClick="btnAdicionarProduto_Click" Text="Adicionar" />
                    </div>
                </div>
            </div>
            <div>
                <asp:GridView ID="grdItensPedido" runat="server" CssClass="table table-striped table-bordered" AutoGenerateColumns="false" AutoGenerateDeleteButton="true"
                    OnRowDeleting="grdItensPedido_RowDeleting">
                    <Columns>
                        <asp:BoundField DataField="Id" HeaderText="Id" />
                        <asp:BoundField DataField="Descricao" HeaderText="Produto" />
                        <asp:BoundField DataField="Total" HeaderText="Total" />
                    </Columns>
                </asp:GridView>
            </div>
        </fieldset>
    </div>
    <div runat="server" id="divPagamentos" visible="false"> 
        <fieldset>
            <legend>Pagamentos</legend>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="ddlFormapagamento">Forma Pagamento:</label>
                        <asp:DropDownList CssClass="form-control" AutoPostBack="true" OnSelectedIndexChanged="ddlFormapagamento_SelectedIndexChanged" ID="ddlFormapagamento" runat="server" />
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="ddlTipoFrete">Frete:</label>
                        <asp:DropDownList CssClass="form-control" ID="ddlTipoFrete" runat="server" />
                    </div>
                </div>
            </div>
            <p><strong>Total (com desconto):</strong> <span runat="server" id="spnTotaDesconto"></span></p>
        </fieldset>
    </div>
    <ex:ResumoPedido  runat="server" ID="cpnResumoPedido" Visible="false"></ex:ResumoPedido>    
</asp:Content>
